[tool.poetry]
name = "nice"
version = "0.1.0"
description = ""
authors = ["Swa <swa@orbifold.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
nicegui = "^2.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
